### ISSUE TITLE
Best way to create Team model

### ISSUE THREAD

**Issue by nate-r-a** [CrazyOptimist/slack-rails-bot-starter#10]
I'm trying to get this repo set up, but I'm getting stuck on creating the Teams model for the database (I'm using `pg` for this). When I run the server and try to add it to a workspace, I get this:

```ERROR -- : ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "teams" does not exist```

Trying something like `rails g model Team` warns me that `The name 'Team' is either already used in your application or reserved by Ruby on Rails.`

This makes sense, but I'm not sure how to reconcile the two messages. I've never really used Grape, so I imagine I'm just missing something simple. Thanks!

**Comment by crazyoptimist** [comment]
Sorry for the lack of documentation for Active Record use case. Hope this screen capture helps a bit. Collapsed changes are not necessary ones for this boilerplate.

https://user-images.githubusercontent.com/55074937/145165487-18280832-4dd7-41f7-b723-3febde3cb5d5.mp4

As far as I remember, there is a small bug related to a pagination gem in the slack-bot-server-event when using with Active Record, I was planning to patch it before but couldn't have a chance yet.

**Comment by crazyoptimist** [comment]
Did it help, @nate-r-a ?

**Comment by nate-r-a** [comment]
So before I saw your comment, I ended up creating a model based on https://github.com/slack-ruby/slack-ruby-bot-server/blob/master/lib/slack-ruby-bot-server/models/team/mongoid.rb from the original repo. That seems to have worked for me for now, but if I make a new bot I will make use of your changes!

**Comment by crazyoptimist** [comment]
Great!
