### ISSUE TITLE
Turn on/off various different types of integration

### ISSUE THREAD

**Issue by dblock** [CrazyOptimist/slack-rails-bot-starter#2]
Newer bots can be entirely event based, without any real-time components. Need a feature in slack-ruby-bot-server to make RTM optional (possibly by doing https://github.com/slack-ruby/slack-ruby-bot-server/issues/124) and explain here how to turn on/off various types of integrations.

**Comment by crazyoptimist** [comment]
Got you.
And I'm still waiting the new release of slack-ruby for the slack api v2.
We are still  stuck on the legacy version.
I remember someone was already working on it...
Are we close to the new release or something else?

**Comment by dblock** [comment]
Do you mean switching slack-ruby-bot-server to use oauth v2? I am certainly not working on it and don't think anyone is. The API is available in the client since https://github.com/slack-ruby/slack-ruby-client/pull/303.

**Comment by dblock** [comment]
There was https://github.com/slack-ruby/slack-ruby-bot-server/pull/125 but it was left unfinished, please feel free to pick it up!

**Comment by crazyoptimist** [comment]
Yeah, I was just pointing that.
Simply put, I think we need to make using v2 as default mode.
Let me comeback and pick it up sooner.

**Comment by dblock** [comment]
I am pretty much done with https://github.com/slack-ruby/slack-ruby-bot-server/pull/129 which removes the real-time portion of slack-ruby-bot-server. For apps that don't need it, one just needs to set the oauth scopes like this:

```ruby
SlackRubyBotServer.configure do |config|
  config.oauth_scope = ['channels:read', 'chat:write:user']
end
```

That should be it, and slack-ruby-bot-server-events works out of the box. 

I recommend updating this tutorial and removing the RTM part altogether.

**Comment by crazyoptimist** [comment]
Gotcha!

**Comment by crazyoptimist** [comment]
>That should be it, and slack-ruby-bot-server-events works out of the box.

Did you confirmed it with the new version of slack app?

**Comment by dblock** [comment]
> > That should be it, and slack-ruby-bot-server-events works out of the box.
> > Did you confirmed it with the new version of slack app?

I didn't, so you get the v2 auth problem. I'll look into it.
